### ISSUE TITLE
... how do i know which data mean what ... ?

### ISSUE THREAD

**Issue by HandLmModel** [cansik/mediapipe-osc#3]
Hello Sir,
well, this really seems to work, thumbs up !!!
I can get the OSC-data into my musical environment.
Alone, the data are pretty anonymous, so i don't know how to route the arguments to the right address.
Is there any "path" you can recommend how to know which data mean what ?
Sry for me being so clumsy ...,, best regards !
P.S.: Your program works fine with dataclasses0.6; version 0.8 doesn't seem to be supported ...

**Comment by cansik** [comment]
You have to read the documentation to understand the data. Check out the [Format](https://github.com/cansik/mediapipe-osc#format) section.

But to be honest, this is not meant to be used directly as an audio-parameter controller, because you get just the coordinates of the different keypoints. For controlling an instrument, you would usually need something like the distance between two keypoints.

**Comment by HandLmModel** [comment]
... yes, just got it!
Well, this thing has got the potential to get me out of pandemic depressions !
May i contact you ?
Best regards !
